apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: blog
build:
  artifacts:
    - image: naohirokurasawa/blog
      custom:
        buildCommand: docker build --build-arg NPM_TOKEN=${NPM_TOKEN} .
deploy:
  kubectl:
    manifests:
      - k8s/development.yaml
      - k8s/service.yaml
